### PR TITLE
Add fpcomplete repositories to whitelist.

### PR DESCRIPTION
**Pull request by jhance**
These repositories contain releases of Stack, the tool used to
build Haskell packages.

This is a fixed up version of PR #7, which has been in waiting for
over a year now and is extremely important to Haskell
developers.

@BanzaiMan please take a look at this, we have been waiting forever.

/cc @Blaisorblade

### CODE REVIEW

**Comment by Blaisorblade** [comment]
FWIW, I've reviewed the original PR and its review comments, and confirm this PR satisfied them. Hence LGTM.

**Comment by Blaisorblade** [comment]
Also, thanks to @jhance for fixing this up!

**Comment by BanzaiMan** [comment]
Sorry for the delay. If you need additional APT sources, please use GCE with `sudo: required`.

**Comment by gpyh** [comment]
The is ambiguous. Does this mean it is going to be merged, or the opposite?

**Comment by jhance** [comment]
It seems to mean it won't be merged, because he is saying to not use the container environment as a workaround instead of a solution.

**Comment by Blaisorblade** [comment]
Uh. Apparently this process is being shut down for lack of resources, see #173 (dropping https://github.com/travis-ci/apt-source-whitelist#source-approval-process) and 
https://github.com/travis-ci/docs-travis-ci-com/pull/390.

At least now we know we're stuck with our workarounds. Thanks anyway @jhance for opening the new PR!

**Comment by jhance** [comment]
But there have been apt repos added to the whitelist since that issue was created (around a year ago)

**Comment by Blaisorblade** [comment]
OK, I'm not implying this is somehow "fair"—shutting the process down is more honest at least. I guess the process might have been some variant of "well, we do trust this package is trustworthy because <insert heuristic here>" and this heuristic doesn't apply to stack somehow.

I do wonder about the security model Travis is using, if the concern is about breaches to the sandboxing—stack has no setuid binaries and is written in a memory-safe language. (This whole whitelist always sounded fishy to me).

But I'm also not a paying customer, so I don't consider myself entitled to anything. And Stack has a reasonable workaround, as opposed to other people suffering from this:
https://github.com/travis-ci/docs-travis-ci-com/commit/cadab12b5a2c8d54b06f89832506ed6bf10e4e72#commitcomment-13989218

**Comment by gpyh** [comment]
This is disappointing. Haskell support is really lacking in Travis.
@BanzaiMan please take a look at the bottom on this page: https://docs.travis-ci.com/user/languages/haskell

These are supposed to be real life examples of projects using Travis' Haskell support. However, **none** of them actually use the specific Haskell features provided by Travis. They must rely on complicated custom builds to do things that are completely trivial with other platforms. Note the irony: stack *itself*, as a Haskell project, is advertised in your documentation.

I urge the Travis team to reconsider. Stack is not just some random software that we'd like to see whitelisted for our convenience. It is the opportunity for you to fix the sorry state of Haskell support in Travis by providing the most modern build tool for Haskell project.

**Comment by jhance** [comment]
@BanzaiMan I removed the non-trusty/precise repositories from this PR. (Let me know if I wasn't supposed to remove wily and xenial)

**Comment by Blaisorblade** [comment]
Great! Thanks @BanzaiMan !!!

**Comment by jhance** [comment]
http://i.imgur.com/7drHiqr.gif?noredirect

**Comment by Blaisorblade** [comment]
FTFY:

**Pull request merged**
