### PR TITLE
add ppa:raphink/augeas to whitelist

### PR DESCRIPTION
**Pull request by igalic**
This pr addresses #101

### CODE REVIEW

**Comment by raphink** [comment]
See also https://github.com/travis-ci/travis-ci/issues/3633

**Comment by igalic** [comment]
hah. i did a quick-search of 'raphink' in prs and didn't find anything :O

**Comment by igalic** [comment]
@emdantrim promised me to merge this, then went for lunch and was never seen again :(

**Comment by emdantrim** [comment]
https://github.com/travis-ci/apt-source-whitelist/pull/179

**Comment by igalic** [comment]
\o/ @emdantrim \o/

**Pull request closed without merging**
