### PR TITLE
add universe-factory repo

### PR DESCRIPTION
**Pull request by flokli**

### CODE REVIEW

**Comment by flokli** [comment]
Seems like the travis build is failing, as the [llvm apt mirrors](http://llvm.org/apt/) are switched off.

**Comment by flokli** [comment]
rebased this after llvm mirrors get fixed, travis now green. ping @BanzaiMan

**Comment by flokli** [comment]
ping ;-)

**Comment by BanzaiMan** [comment]
I am sorry to inform you, but we are not accepting PRs on this repo. If you need this source, please use `sudo`-enabled infrastructure to achieve your goal. Thanks.

**Pull request closed without merging**
