### PR TITLE
Add mysql-5.7-precise and mysql-5.7-trusty

### PR DESCRIPTION
**Pull request by sodabrew**

### CODE REVIEW

**Comment by AdrianLC** [comment]
Please approve this :+1:

**Comment by abelgvidal** [comment]
yep, it would be useful

**Comment by edmorley** [comment]
This looks correct to me after checking against:
http://dev.mysql.com/doc/mysql-apt-repo-quick-guide/en/#repo-qg-apt-repo-manual-setup
http://dev.mysql.com/doc/refman/5.7/en/checking-gpg-signature.html

@BanzaiMan, I don't suppose you know when you might be able to take a look at this? :-)

**Comment by BanzaiMan** [comment]
Could someone try this on `sudo`-enabled VMs, and report the result? My understanding is that, if there is an existing MySQL installation, installing MySQL over it can cause problems.

**Comment by lipanski** [comment]
would be great to have this - mainly because it's the only way to test against MySQL 5.7 without doing `sudo`. our problem with `sudo` is that the machines on GCE aren't behind a NAT and can't be whitelisted.

**Comment by baloo** [comment]
@BanzaiMan Here is a build like you requested:
https://github.com/baloo/test-travis-mysql
https://travis-ci.org/baloo/test-travis-mysql/builds/216152867

Apt will remove and replace the existing mysql config:
```
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.bm8c5xq6ef --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg --keyserver pgp.mit.edu --recv-keys 5072E1F5
gpg: requesting key 5072E1F5 from hkp server pgp.mit.edu
gpg: key 5072E1F5: public key "MySQL Release Engineering <mysql-build@oss.oracle.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
Preconfiguring packages ...
(Reading database ... 88286 files and directories currently installed.)
Removing mysql-server-5.6 (5.6.33-0ubuntu0.14.04.1) ...
mysql stop/waiting
Removing mysql-client-5.6 (5.6.33-0ubuntu0.14.04.1) ...
Removing mysql-client-core-5.6 (5.6.33-0ubuntu0.14.04.1) ...
Removing mysql-server-core-5.6 (5.6.33-0ubuntu0.14.04.1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
(Reading database ... 88058 files and directories currently installed.)
Preparing to unpack .../mysql-common_5.7.17-1ubuntu14.04_amd64.deb ...
Unpacking mysql-common (5.7.17-1ubuntu14.04) over (5.5.53-0ubuntu0.14.04.1) ...
Selecting previously unselected package libmysqlclient20:amd64.
Preparing to unpack .../libmysqlclient20_5.7.17-1ubuntu14.04_amd64.deb ...
Unpacking libmysqlclient20:amd64 (5.7.17-1ubuntu14.04) ...
Preparing to unpack .../libmysqlclient-dev_5.7.17-1ubuntu14.04_amd64.deb ...
Unpacking libmysqlclient-dev (5.7.17-1ubuntu14.04) over (5.5.53-0ubuntu0.14.04.1) ...
Selecting previously unselected package mysql-community-client.
Preparing to unpack .../mysql-community-client_5.7.17-1ubuntu14.04_amd64.deb ...
Unpacking mysql-community-client (5.7.17-1ubuntu14.04) ...
Selecting previously unselected package mysql-client.
Preparing to unpack .../mysql-client_5.7.17-1ubuntu14.04_amd64.deb ...
Unpacking mysql-client (5.7.17-1ubuntu14.04) ...
Selecting previously unselected package libmecab2.
Preparing to unpack .../libmecab2_0.996-1.1_amd64.deb ...
Unpacking libmecab2 (0.996-1.1) ...
Selecting previously unselected package mysql-community-server.
Preparing to unpack .../mysql-community-server_5.7.17-1ubuntu14.04_amd64.deb ...
.
Unpacking mysql-community-server (5.7.17-1ubuntu14.04) ...
Selecting previously unselected package mysql-server.
Preparing to unpack .../mysql-server_5.7.17-1ubuntu14.04_amd64.deb ...
Unpacking mysql-server (5.7.17-1ubuntu14.04) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for ureadahead (0.100.0-16) ...
Setting up mysql-common (5.7.17-1ubuntu14.04) ...
update-alternatives: using /etc/mysql/my.cnf.fallback to provide /etc/mysql/my.cnf (my.cnf) in auto mode
update-alternatives: warning: not replacing /etc/mysql/my.cnf with a link
Setting up libmysqlclient20:amd64 (5.7.17-1ubuntu14.04) ...
Setting up libmysqlclient-dev (5.7.17-1ubuntu14.04) ...
Setting up mysql-community-client (5.7.17-1ubuntu14.04) ...
Setting up mysql-client (5.7.17-1ubuntu14.04) ...
Setting up libmecab2 (0.996-1.1) ...
Setting up mysql-community-server (5.7.17-1ubuntu14.04) ...
Configuration file '/etc/apparmor.d/usr.sbin.mysqld'
 ==> Deleted (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
 ==> Keeping old config file as default.
Installing new version of config file /etc/init.d/mysql ...
update-alternatives: using /etc/mysql/mysql.cnf to provide /etc/mysql/my.cnf (my.cnf) in auto mode
No directory, logging in with HOME=/
mkdir: cannot create directory ‘//.pyenv’: Permission denied
mkdir: cannot create directory ‘//.pyenv’: Permission denied
...
 * MySQL Community Server 5.7.17 is started
Processing triggers for ureadahead (0.100.0-16) ...
Setting up mysql-server (5.7.17-1ubuntu14.04) ...
Processing triggers for libc-bin (2.19-0ubuntu6.9) ...
```

**Comment by baloo** [comment]
@BanzaiMan Any chance to get this merged? If there is anything I can do for that, please let me know.

**Comment by BanzaiMan** [comment]
Sorry for the delay, everyone.

**Comment by edmorley** [comment]
I tried this with a trusty container job, using:
```yaml
addons:
  apt:
    sources:
      - sourceline: 'deb http://repo.mysql.com/apt/ubuntu/ trusty mysql-5.7'
    packages:
      - mysql-server
```

Unfortunately the existing mysql-5.6 instance is running at time of installation and so mysq-5.7 doesn't start:
https://travis-ci.org/mozilla/treeherder/jobs/224020244#L128

The APT step also took 196 seconds (though perhaps some of this is the installer waiting for mysqld to no longer be running), which negates the benefits of using the containers instead of the sudo-enabled jobs.

**Comment by baloo** [comment]
the travis output is weird:
```
Removing mysql-server-5.6 (5.6.33-0ubuntu0.14.04.1) ...
Removing mysql-client-5.6 (5.6.33-0ubuntu0.14.04.1) ...
Removing mysql-client-core-5.6 (5.6.33-0ubuntu0.14.04.1) ...
Removing mysql-server-core-5.6 (5.6.33-0ubuntu0.14.04.1) ...
```
while: 
```
.2017-04-20T16:20:12.906061Z mysqld_safe A mysqld process already exists
................................................................................................................................................................................... * MySQL Community Server 5.7.18 did not start. Please check logs for more details.
```
The 200 seconds things is the timeout of the `service mysql start`. What I don't get is that the mysql5.6 removal should have stopped mysqld. And the configure step of mysql 5.7 clearly states otherwise.

**Comment by edmorley** [comment]
> What I don't get is that the mysql5.6 removal should have stopped mysqld

Agreed, especially since the MySQL APT docs suggest that the upstream installer supports upgrading a distro release:
https://dev.mysql.com/doc/mysql-apt-repo-quick-guide/en/#repo-qg-apt-replacing

**Comment by baloo** [comment]
well, if there is a problem, then it's with `mysql-server-5.6 (5.6.33-0ubuntu0.14.04.1)` which would have been supposed to stop mysqld and did not.

**Comment by salilgupta1** [comment]
Has anyone come across a resolution for this problem? I'm running into the same issue:
`mysqld_safe A mysqld process already exists`

**Comment by edmorley** [comment]
Ah I spoke too soon about being able to use `language: bash` as a workaround -- turns out the docker builds only ever map to amethyst or garnet, never connie, I'd just misread the logs.

Also this morning I can reproduce again -- retriggers of a working job now hang again. eg:
https://travis-ci.org/mozilla/treeherder/jobs/250594247

This is very strange. The only thing I can thing of is that this is some kind of race condition which is affected by the relative load of the Travis worker running the job at the time?

**Pull request merged**
