### PR TITLE
Add LLVM repos for Trusty

### PR DESCRIPTION
**Pull request by poletti-marco**
See https://github.com/travis-ci/apt-source-whitelist/issues/199

### CODE REVIEW

**Comment by mpark** [comment]
+1

**Comment by poletti-marco** [comment]
Could you please merge this? I don't have write access so I can't do the merge myself, even though there are no conflicts.

**Comment by rhysd** [comment]
+1

**Comment by poletti-marco** [comment]
This got two +1s, the last one over 1 week ago, but still noone has merged this into master. I don't have write access so I can't initiate the merge myself. Can someone please do so?

**Comment by roidrage** [comment]
@poletti-marco Sorry, our team is on well-deserved holidays since last week, and we'll get back to you next week.

**Comment by poletti-marco** [comment]
Ok, no worries. Thanks for the update.

**Comment by genbattle** [comment]
+1

**Comment by pwnall** [comment]
+1

**Comment by fjricci** [comment]
+1

**Comment by sas** [comment]
Hey everyone, is it possible to get this one in? It would be really helpful so we can move testing of facebook/ds2 to the docker infra. Thanks!

**Comment by h-2** [comment]
@poletti-marco  can you add llvm-snapshot, too? Thanks!

@roidrage hope you had a great :christmas_tree:  break :) 
+1 from me for this repo, too, very important...

**Comment by smessmer** [comment]
+1

**Comment by simonkrogmann** [comment]
+1

**Comment by poletti-marco** [comment]
@h-2: is there an official llvm-snapshot repo?
I've searched for that, but the only thing I could find were random people's PPAs, nothing official.


@Travis people: could you please merge this? It's a very simple change, I don't have permissions to merge to master myself.

**Comment by h-2** [comment]
@poletti-marco sure, just check: http://llvm.org/apt/trusty/pool/main/l/
It has the same links as the other ones, just with snapshot instead of version number.

**Comment by poletti-marco** [comment]
@h-2: it's not here though:
http://llvm.org/apt/trusty/dists/

And adding this line to /etc/apt/sources.list:
deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-snapshot main

On a trusty installation causes errors like:
Err http://llvm.org llvm-toolchain-trusty-snapshot/main amd64 Packages
404  Not Found
[...]
W: Failed to fetch http://llvm.org/apt/trusty/dists/llvm-toolchain-trusty-snapshot/main/binary-  404  Not Found

Maybe it was there previously but then it was deleted? (not sure why it's still in the place you mentioned though)
Or maybe the required deb line is different?
If you have access to a Trusty installation, do you have a deb line that works?

**Comment by rhysd** [comment]
`apt` package for LLVM 3.6 might be deleted because it is too old.

In [instruction page](http://llvm.org/apt/), how to install LLVM 3.7 and LLVM 3.8 are described.

**Comment by h-2** [comment]
> @h-2: it's not here though:
> http://llvm.org/apt/trusty/dists/

> And adding this line to /etc/apt/sources.list:
> deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-snapshot main 

it looks like the dist without version number includes the snapshots:
http://llvm.org/apt/trusty/dists/llvm-toolchain-trusty/main/binary-amd64/Packages

I can't verify though, because I don't have any ubuntu installs...

**Comment by rhysd** [comment]
Hey,

[LLVM 3.8](http://llvm.org/) was released.  LLVM 3.8 package seems not to be included yet, but it will be done soon, I think.

And I wonder why this PR takes so much time to merge.

**Comment by mavam** [comment]
@poletti-marco Can you update the PR to include 3.8 as well?

**Comment by poletti-marco** [comment]
Now added the 3.8 repo and resolved the merge conflicts with master.

**Comment by mavam** [comment]
Great!

I'm not sure what the merge policy in this repo is, but it may make sense to rebase onto master and squash your commits into a single one.

**Comment by mavam** [comment]
It looks like LLVM 3.8 for precise [just made it in](https://github.com/travis-ci/apt-source-whitelist/pull/255).

Does anyone have an idea what holds this one back?

**Comment by poletti-marco** [comment]
@mavam: I don't know what the merge policy in this repo is, but TBH after 4 months of waiting I don't know if this will ever be merged (not that I'm aware of any issues or controversy, this was just ignored AFAIK).
If some Travis CI people actually start getting serious in merging this and they tell me they have a "linear history" policy I can rebase/squash this PR then.

**Comment by mavam** [comment]
> If some Travis CI people actually start getting serious in merging this and they tell me they have a "linear history" policy I can rebase/squash this PR then.

Makes sense.

The sad part is, leaving it open and ignoring it is wasting everyone's cycles. A clear *yes* or *no* would be much more productive. If this PR gets rejected, we hopefully will now why and can move on. If it gets merged, then great. Clearly, the Travis folks merge here and there, so it's really just a communication problem.

**Comment by BanzaiMan** [comment]
For Trusty, please use `sudo` to manage apt packages.

**Comment by cardoe** [comment]
Thank you!

**Comment by sas** [comment]
Lol.

On Sunday, April 24, 2016, poletti-marco <notifications@github.com> wrote:

> Closed #205 <https://github.com/travis-ci/apt-source-whitelist/pull/205>.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/travis-ci/apt-source-whitelist/pull/205#event-638956365>
>


-- 
Stephane Sezer

**Comment by solarce** [comment]
A note about Trusty support right now. 

The `apt` addon is only really needed for the container-based Precise builds, we don't yet support Trusty on that platform.

Our Trusty builds have sudo enabled so you can add and install any sources and packages you want to via `before_install:`, `install:`, etc

**Comment by mavam** [comment]
Too bad Trusty doesn't have that support (yet). But a concrete statement is certainly helpful.

> Our Trusty builds have sudo enabled so you can add and install any sources and packages you want to via `before_install:`, `install:`, etc

Looks like we'll be doing this then for a while:

```yaml
before_install:
  - wget -nv -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-add-repository -y 'deb http://llvm.org/apt/trusty llvm-toolchain-trusty-3.6 main'
  - sudo apt-add-repository -y 'deb http://llvm.org/apt/trusty llvm-toolchain-trusty-3.7 main'
  - sudo apt-add-repository -y 'deb http://llvm.org/apt/trusty llvm-toolchain-trusty-3.8 main'
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y clang-3.6 clang-3.7 clang-3.8
```

**Pull request closed without merging**
