### PR TITLE
Update LLVM APT repositories to new URL

### PR DESCRIPTION
**Pull request by OXINARF**
Announcement: https://groups.google.com/d/msg/llvm-dev/BDvXst08TVo/whAEoqIDEwAJ

### CODE REVIEW

**Comment by sylvestre** [comment]
ping?

**Comment by yuriks** [comment]
re-ping. The 3.9 repo has been release in the meantime, too.

**Comment by blair1618** [comment]
@travis-ci looking forward to having a working LLVM toolchain on Travis!

**Comment by BanzaiMan** [comment]
Thanks. I've overlooked this and fixed it in https://github.com/travis-ci/apt-source-whitelist/commit/fd42d2551c4dee26452d807e81ef6aa4c17e5def.

**Pull request closed without merging**
