### PR TITLE
Whitelist repository llvm-toolchain-xenial for Ubuntu / unlock Clang 10 on Ubuntu xenial

### LINKED ISSUE #407: Please whitelist repository "llvm-toolchain-xenial" for Clang >=9 on Ubuntu xenial
Hi!

`llvm-toolchain-trusty` (without a number) for Clang 9 on Ubuntu `trusty` [is there](https://github.com/sylvestre/apt-source-whitelist/blob/ad239bcda10380d865e36148a7e8dbf8ea1ea0db/ubuntu.json#L292-L297), but `llvm-toolchain-xenial` (without a number) for Clang 9 on Ubuntu `xenial` — as I read https://apt.llvm.org/ — is still [disallowed](https://travis-ci.org/uriparser/uriparser/builds/555952912#L160).

Any chance it could be added?

Thanks!

Related: #392 #399

### PR DESCRIPTION
**Pull request by hartwork**
Key downloaded from https://apt.llvm.org/llvm-snapshot.gpg.key

To fix #407

Similar to #399 (Clang 8)

### CODE REVIEW

**Comment by hartwork** [comment]
Anyone?

**Comment by concatime** [comment]
`llvm-toolchain-xenial-9` is [out](//apt.llvm.org).

**Comment by concatime** [comment]
#411

**Comment by zhiayang** [comment]
would be nice to have; travis on linux is currently unusable because of this

**Comment by hartwork** [comment]
Thanks to https://github.com/bitfieldaudio/OTTO/pull/176 for teaching me to do it *without* relying on `apt-source-safelist`! :+1: :pray: 

This repository right here seems dead the way I read the readme (shown below) and judging from the date of the latest commit on `master`… so I'll close this pull request.

dead_readme

**Pull request closed without merging**
