### PR TITLE
Marks chrome repo as 64bit arch type

### LINKED ISSUE #256: Google Chrome deb may need [arch=amd64]
At the moment I'm having trouble across a few different repos in grabbing google-chrome. `apt-get install` seems to be struggling with there not being a 32bit version of Chrome.

    W: Failed to fetch http://dl.google.com/linux/chrome/deb/dists/stable/Release  Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)

Chrome has stopped making 32 bit builds of Chrome which is likely causing the issue see: http://www.omgubuntu.co.uk/2016/01/google-chrome-linux-32-bit-discontinued

[Looking through this question / answer](http://askubuntu.com/questions/724093/no-more-updates-for-google-chrome-apt-get-update-error), it would seem like the chrome entry needs to change from:

      {
        "alias": "google-chrome",
        "sourceline": "deb http://dl.google.com/linux/chrome/deb/ stable main",
        "key_url": "https://dl-ssl.google.com/linux/linux_signing_key.pub"
      },

to:

      {
        "alias": "google-chrome",
        "sourceline": "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main",
        "key_url": "https://dl-ssl.google.com/linux/linux_signing_key.pub"
      },

I'd raise a PR but I don't know enough about debian packages and repos to comment on how far reaching this change would be, hence raising this issue.

If it sounds like a good suggestion then please let me know and I'll put together a PR.

Matt

### PR DESCRIPTION
**Pull request by gauntface**
Fixes #256

### CODE REVIEW

**Comment by myitcv** [comment]
@gauntface this is the correct change - I've had to make a similar change in multiple places (including our container builder). :+1: from my perspective

**Comment by solarce** [comment]
Looks good :sheep: :it:

**Comment by myitcv** [comment]
@solarce thanks

**Comment by myitcv** [comment]
At the time of writing, [`google-chrome-stable` installs fine](https://travis-ci.org/myitcv/travis-install-chrome/builds/121694008), but [`google-chrome-beta` fails](https://travis-ci.org/myitcv/travis-install-chrome/builds/121694077) because of an unmet `lsb-base` dependency:

```
The following packages have unmet dependencies:
 google-chrome-beta : Depends: lsb-base (>= 4.1) but 4.0-0ubuntu20.3 is to be installed
E: Unable to correct problems, you have held broken packages.
```

Anyone got any ideas on how/if that can be fixed?

**Comment by jhen0409** [comment]
@myitcv I have the same problem, but `google-chrome-stable` also fails now.

[My build](https://travis-ci.org/jhen0409/react-chrome-extension-boilerplate#L150)

**Comment by myitcv** [comment]
[Confirmed in my test repo](https://travis-ci.org/myitcv/travis-install-chrome/builds/121694008)

@solarce - any idea how we can deal with this `lsb-base` dependency not being met?

**Comment by gauntface** [comment]
Upgrade to trusty. Just add:

Sudo: required
Dist: trusty

**Comment by myitcv** [comment]
@gauntface thanks, I hadn't thought of that option. Obvious now 👍 

[`google-chrome-stable`](https://travis-ci.org/myitcv/travis-install-chrome/builds/123681155) now fixed, and [`google-chrome-beta`](https://travis-ci.org/myitcv/travis-install-chrome/builds/123681115) also works.

**Comment by gauntface** [comment]
No worries, it took me ages to realise it as well :)

**Comment by solarce** [comment]
Unfortunately, since Google has dropped support for Ubuntu 12.04 with the release of Chrome 50, and Google does not keep older versions in their apt repositories, we're not able to provide any assistance with trying to run Chrome on Precise and can only suggest you try Trusty, as outlined above.

**Pull request merged**
