### PR TITLE
adding clang 7.0 to source white list

### PR DESCRIPTION
**Pull request by prince-chrismc**
http://apt.llvm.org/

### CODE REVIEW

**Comment by prince-chrismc** [comment]
https://github.com/travis-ci/travis-ci/issues/10069 

There's also an issue that's been opened on the main repo

**Comment by prince-chrismc** [comment]
just noticed these are no longer processed. RIP me.

if any1 see's this hopefully you can merge it for me =)

**Comment by sylvestre** [comment]
The name is 7 now, not 7.0.
I created https://github.com/travis-ci/apt-source-safelist/pull/392 which fixes that.

**Review by Breadcorn — COMMENTED** [review]
@ogbread626

**Pull request closed without merging**
