### PR TITLE
Add llvm 3.8 repo to make available clang-3.8

### LINKED ISSUE #254: APT source whitelist request for llvm-toolchain-precise-3.8
Now that LLVM/Clang 3.8 has been released, please add:

deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.8 main
deb-src http://llvm.org/apt/precise/ llvm-toolchain-precise-3.8 main

(also for trusty, etc. if you like)

### PR DESCRIPTION
**Pull request by springmeyer**
closes #254

/cc @BanzaiMan

### CODE REVIEW

**Comment by dawagner** [comment]
clang-3.8 used to be available in the llvm-toolchain-precise repository but it is no longer the case. That means that builds using clang-3.8 are now broken, and until this PR is merged.

**Comment by ldionne** [comment]
I just encountered the same problem as @dawagner. This will cause a lot of trouble for C++ projects, so please merge this ASAP.

**Comment by CaseyCarter** [comment]
+1. Thanks to [LLVM Bug 22757](https://llvm.org/bugs/show_bug.cgi?id=22757), the clang 3.7 packages don't contain the runtime libraries for the sanitizers. The resolution enabled sanitizers again in clang 3.8 packages - it would be great to have them available.

**Comment by Morwenn** [comment]
Same problem here. The sooner it gets merged, the better.

**Comment by JohanEngelen** [comment]
Same problem for the LDC project.

**Comment by dawagner** [comment]
Thanks :)

**Comment by Morwenn** [comment]
Yep, it fixed the build, thanks :)

**Comment by ldionne** [comment]
Thanks, fixed on my side too.

**Pull request merged**
